[workspace]

members = [
    "01_hello_world",
    "02_guessing_game/02_guessing_game_once",
    "02_guessing_game/02_guessing_game_multi",
    "03_concept/03_variables",
    "03_concept/03_types",
    "03_concept/03_compound_types",
    "03_concept/03_functions",
    "03_concept/03_control_flow",
    "04_ownership/04_owner",
    "04_ownership/04_reference",
    "04_ownership/04_slice",
]